# Site settings
title: Student Server Space
description: > #
  Student Server Space
baseurl: "/sss"
url: "https://matthewwang.me"
repo: "https://github.com/studentserverspace/website/"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
highlighter: rouge


# Collections
collections:
  docs:
    output: true
    layout: docs
